// export const REQUEST_POSTS = 'REQUEST_POSTS'
// export const RECEIVE_POSTS = 'RECEIVE_POSTS'
// export const SELECT_SUBREDDIT = 'SELECT_SUBREDDIT'
// export const INVALIDATE_SUBREDDIT = 'INVALIDATE_SUBREDDIT'


export const GET_MEASUREMENTS = 'GET_MEASUREMENTS'
export const GET_MEASUREMENT_SYSTEM = 'GET_MEASUREMENT_SYSTEM'
export const SHOW_ALL_MEASUREMENTS = 'SHOW_ALL_MEASUREMENTS'
export const FILTER_ITEMS = 'FILTER_ITEMS'
