export const RELATION_NUTRITIONS_UNITS = 'RELATION_NUTRITIONS_UNITS'
export const GET_NUTRITIONS_V_ONE = 'GET_NUTRITIONS_V_ONE'
export const GET_NUTRITIONS_V_TWO = 'GET_NUTRITIONS_V_ONE'
export const GET_NUTRITIONS_V_THREE = 'GET_NUTRITIONS_V_THREE'
