GET_RECIPE_DETAILS (ID)
RECIPE_LIST_VEIW (IDs)
GET_RANDOM (one or few) -> by two methods
GET_5_RANDOM INGREDIENTS
GET_RECIPE (id)

RECIPE_INGREDIENTS_RELATION



export const VIEW_CALENDAR = 'VIEW_CALENDAR'
export const VIEW_DAY = 'VIEW_DAY'
export const VIEW_WEEK = 'VIEW_WEEK'
export const VIEW_DETAILS = 'VIEW_DETAILS'
export const CHANGE_DATE = 'CHANGE_DATE'
export const CHANGE_TIME = 'CHANGE_TIME'


export const URL_FULL_RECIPE = 'URL_FULL_CALENDAR'

export const URL_VIEW_RECIPE_DETAILS = 'URL_DETAILS'

export const URL_ADD_RECIPE = 'URL_ADD_EVENT'
export const URL_DELETE_RECIPE = 'URL_DELETE_EVENT'
export const URL_EDIT_RECIPE  = ''






URL_RECIPE_DISPLAY_5_RECIPES
URL_GET_ALL_GROCERY_LISTS
URL_GET_DEPARTMENTS_CLEAN
URL_GET_GROCERY_BY_ID
URL_GET_FULL_GROCERY (name)
URL_GET_GROCERY_DATA from id
URL_GET_GROCERY_LISTS_WITH_DEP_ING_KEY
URL_GET_ALL_INGREDIENTS_BY_ONE_DEP_KEY

GET_ULTIMATE_GL
GET_GL_WITH_USER
GET_INGREDIENT_SAMPLE
GET_GROCERY_LISTS_WITH_DEPINGKEY





export const FILES_RECIPE = 'URL_EDIT_EVENT'
export const FILES_CALENDAR = 'FILES_CALENDAR'
export const FILES_WEEKLY_MENU = 'FILES_WEEKLY_MENU'
