// import {
//   // allergies,
//   course,
//   cuisine,
//   departments,
//   diet,
//   grocery,
//   holiday,
//   ingredients,
//   ingredients1,
//   ingredients3,
//   favorites,
//   items,
//   mealCalendar,
//   firstVeganGLMC,
//   measurements,
//   menu,
//   recipes,
//   nutritions,
//   nutritions2,
//   users,
//   userGrocery,
//   ultimateGroceryList,
//   groceryListWithUserRelations,
//   dbIngredients
// } from './files'

import files from './files'
export default files

// export default {
//   allergies,
//   course,
//   cuisine,
//   departments,
//   diet,
//   grocery,
//   holiday,
//   ingredients,
//   ingredients1,
//   ingredients3,
//   favorites,
//   items,
//   mealCalendar,
//   firstVeganGLMC,
//   measurements,
//   menu,
//   recipes,
//   nutritions,
//   nutritions2,
//   users,
//   userGrocery,
//   ultimateGroceryList,
//   groceryListWithUserRelations,
//   dbIngredients
// }
